/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    kotlin("jvm") version "2.1.10"
    application
    id("com.github.johnrengelman.shadow") version "8.1.1"
    id("org.jlleitschuh.gradle.ktlint") version "11.5.0"
}

group = "com.cookieanalyzer"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

dependencies {
    implementation("com.github.ajalt.clikt:clikt:3.5.4")
    testImplementation(kotlin("test"))
    testImplementation("io.mockk:mockk:1.13.5")
}

tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.cookieanalyzer.cli.CookieAnalyzerCommandKt"
    }
}

tasks.shadowJar {
    archiveBaseName.set("cookie-analyzer")
    archiveClassifier.set("")
    archiveVersion.set("")
}

tasks.test {
    useJUnitPlatform()
}

kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("MainKt")
}
